### ISSUE TITLE
GLTF 2.0 importer?

### ISSUE THREAD

**Issue by ghost** [floooh/oryol-tools#6]
Hello Andre,
will it be possible to have a gltf 2.0 model importer in your framework?

kind regards
david

**Comment by floooh** [comment]
Very unlikely because it's a lot of work, and similar to FBX it's hard to create a converter which accepts all possible GLTF files. There's a great GLTF parsing header https://github.com/jkuhlmann/cgltf which gets you halfway there, but it's still a lot of work.

(PS: if you need some code to get started, have a look at this sokol-headers sample: https://github.com/floooh/sokol-samples/blob/master/sapp/cgltf-sapp.c

**Comment by ghost** [comment]
thanks a lot for the update
