### ISSUE TITLE
zsh: segmentation 

### ISSUE THREAD

**Issue by ghost** [floooh/oryol-tools#7]
Dear Team ,
the following command line trigger : 
**./oryol-export -config ./test_config.toml -model teapot.fbx -out teapot.omsh**
zsh: segmentation fault  ./oryol-export -config ./test_config.toml -model teapot.fbx -out teapot.omsh

may you help?

thank you in advance,
david

**Comment by floooh** [comment]
The oryol-tools aren't really supported, they've been more like an unfinished experiment. You might have a bit more luck with the oryol-conv3d tool since this has more recent changes, but I'd recommend writing your own asset exporter tools instead.

The segmentation fault in oryol-export happens here:

https://github.com/floooh/oryol-tools/blob/9f0719343718d379d0cb52838260da78466e4ba7/src/ExportUtil/Config.cc#L175

This code looks obviously wrong because it tries to change the first item in a std::vector, but this std::vector is empty (as I said, this stuff is all pretty much unfinished and abandodend).
